SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEORID_ADDED_VELOCITY = 1.2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

COUNTER_X = 0
COUNTER_Y = 0
COUNTER_FONT = None
COUNTER_SIZE = 50

ASTEROID_IMAGES_FOLDER = "./images/"
ASTEROID_IMAGES = ["asteroid_1.png","asteroid_2.png","asteroid_3.png","asteroid_4.png"]